### ISSUE TITLE
stdlib-fpm branch fails to build on Apple M1

### ISSUE THREAD

**Issue by certik** [fortran-lang/stdlib#561] opened 2021-11-12 03:03 UTC
### Description

```
(gf) fortran-lang/stdlib(stdlib-fpm) $ fpm build
 + mkdir -p build/dependencies
Initialized empty Git repository in /Users/certik/repos/fortran-lang/stdlib/build/dependencies/test-drive/.git/
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 31 (delta 5), reused 13 (delta 0), pack-reused 0
Unpacking objects: 100% (31/31), 31.07 KiB | 1.00 MiB/s, done.
From https://github.com/fortran-lang/test-drive
 * branch            HEAD       -> FETCH_HEAD
 + mkdir -p build/gfortran_2A42023B310FA28D
 + mkdir -p build/gfortran_2A42023B310FA28D/stdlib/
 + gfortran -c ././src/stdlib_system.F90  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -J build/gfortran_2A42023B310FA28D -Ibuild/gfortran_2A42023B310FA28D -o build/gfortran_2A42023B310FA28D/stdlib/src_stdlib_system.F90.o
././src/stdlib_system.F90:31:16:

   31 | subroutine sleep(millisec)
      |                1
Warning: ‘sleep’ declared at (1) may shadow the intrinsic of the same name.  In order to call the intrinsic, explicit INTRINSIC declarations may be required. [-Wintrinsic-shadow]
 + gfortran -c ././src/stdlib_kinds.f90  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -J build/gfortran_2A42023B310FA28D -Ibuild/gfortran_2A42023B310FA28D -o build/gfortran_2A42023B310FA28D/stdlib/src_stdlib_kinds.f90.o
 + gfortran -c build/dependencies/test-drive/src/testdrive.F90  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -J build/gfortran_2A42023B310FA28D -Ibuild/gfortran_2A42023B310FA28D -o build/gfortran_2A42023B310FA28D/stdlib/build_dependencies_test-drive_src_testdrive.F90.o
build/dependencies/test-drive/src/testdrive.F90:898:12:

  898 |     real(qp), intent(in) :: actual
      |            1
Error: Kind -1 not supported for type REAL at (1)
compilation terminated due to -fmax-errors=1.
<ERROR> Compilation failed for object " build_dependencies_test-drive_src_testdrive.F90.o "
<ERROR>stopping due to failed compilation
STOP 1
```

### Expected Behaviour

xxxxxxxxxxxxxxxxx

### Version of stdlib

cc641dd3f2e4dd804d5ad1fc2ff770e3998bdc08

### Platform and Architecture

MacOS/ARM

### Additional Information

This form is so hard to fill out that I almost gave up on reporting this.

I would suggest to either get rid of it, or simplify this.

**Comment by zoziha** [comment] 2021-11-12 03:08
May be the same as https://github.com/fortran-lang/stdlib/issues/527 .

**Comment by awvwgk** [comment] 2021-11-12 09:19
Duplicate of https://github.com/fortran-lang/stdlib/issues/527

**Closed by awvwgk** 2021-11-12 09:19 UTC
Labels: bug

**Comment by awvwgk** [comment] 2021-11-12 09:28
@certik Good bug reports are important to help maintainers figure out what the actual problem is. The bug report form is meant to guide reporters to provide at least the required information (compiler, platform, architecture, project version, commands used, logs) to not require the maintainers to chase after those bits. Taking the time to provide a detailed bug report is a good way to help a project improve.

If you think the form is not suitable for your report, there is also a free form template which doesn't impose any constraints on the provided input.

**Comment by certik** [comment] 2021-11-12 22:36
For large established projects that is no doubt the way to go.

For small projects that are trying to become successful, like fpm, my personal priority is in ensuring it's easy to report bugs. So far we haven't had flood of unusable bug reports. So lowering the entry to report bugs can only help.

Also it is very important to encourage people to report bugs, even if not perfectly.

From your feedback, I am actually quite confused: would you prefer me to not report bugs like the above?

**Comment by awvwgk** [comment] 2021-11-12 23:21
> would you prefer me to not report bugs like the above?

I guess there is some misunderstanding between us again, because I don't see how this involves me personally. I'm sorry if I offended you in some way with my comment above when trying to explain the motivation behind the report form.

**Comment by certik** [comment] 2021-11-13 03:29
> I guess there is some misunderstanding between us again

This is the first time I remember having any kind of misunderstanding. I am not offended in any way. I was just trying to provide feedback to improve the bug reporting experience. It is my subjective experience, so it might not generalize to others. If you feel we had some misunderstandings before, please let me know. I am happy to talk anytime.
