### ISSUE TITLE
Compilation problems using CMake and ifort (IFORT) 18.0.3 20180410

### ISSUE THREAD

**Issue by wclodius2** [fortran-lang/stdlib#390] opened 2021-04-18 13:41 UTC
My version of ifort
ifort (IFORT) 18.0.3 20180410
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.
is having trouble compiling `stdlib` when invoked using make. In particular while compiling stdlib_quadrature_simps.f90 I am getting multiple messages of the form
```
    ...stdlib_quadrature_simps.f90(50): error #6284: There is no matching specific function for this generic function reference.   [SIMPS]
                        integral =  simps38(y(1:4), dx) + simps(y(4:6), dx)
    ------------------------------------------------------^
```

FWIW I get no messages when compiling with gfortran 10.2.

**Comment by awvwgk** [comment] 2021-04-18 14:12
Duplicate of https://github.com/fortran-lang/stdlib/issues/299

**Comment by awvwgk** [comment] 2021-04-18 14:13
stdlib currently requires Intel Fortran 19 or newer, not sure how difficult it would be to make it compatible for the previous versions.

**Comment by awvwgk** [comment] 2021-04-18 17:14
Just checked Intel version 18.0.5.20180823, which doesn't throw the above error.

**Comment by wclodius2** [comment] 2021-04-18 18:10
Thanks

**Comment by 14NGiestas** [comment] 2022-05-05 21:50
Closing in favor of #299

**Closed by 14NGiestas** 2022-05-05 21:50 UTC
Labels: duplicate, build: cmake, compiler: ifort
